[env:esp32-c6-lcd-147]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 2MB
board_upload.flash_size = 2MB

lib_deps =
  lvgl/lvgl@^8.3.11

build_flags =
  -I include
  -D LV_CONF_INCLUDE_SIMPLE
  -Wno-error

build_unflags =
  -fuse-cxa-atexit
